/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlopticadelaluz;

import hilos.Reloj;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimerTask;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author lara
 */
public class Principal extends javax.swing.JFrame{
 
     Tablero t = new Tablero(this);
     Producto p = new Producto();
     InicioSesion v = new InicioSesion(this, rootPaneCheckingEnabled);
     Ventas ven = new Ventas();
     Garantias ga = new Garantias();
     Almacen alm = new Almacen();
     
     
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jSplitPane1.setDividerLocation(200);
               jSplitPane1.setRightComponent(t);
                String dateStr = "2018-06-22T10:00:00";
               v.darObjetos(this);
                v.show();
                jLabel1.setForeground(Color.white);
                hora();
              
    }
        
     private static final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

    
    public void parseDate(String dateStr) {
           try {
            Date date = simpleDateFormat.parse(dateStr);
            System.out.println("Successfully Parsed Date " + date);
            this.jLabel1.setText("<html>"+"<h1>"+dateStr+"</h1>"+"</html>");
        } catch (Exception e) {
            e.printStackTrace();
        }
      
    }
    
    
    
    public void hora(){
         
        Reloj re = new Reloj(this);
        Thread hilo1 = new Thread(re);
        hilo1.start();
       	 	   

    }
    
    public void darTexto(String m){
        jLabel1.setText(m);
    }
    
    
    public void mostrarPanelProductos(){
       jSplitPane1.remove(2);
       jSplitPane1.setRightComponent(p); 
    }
    
    public void mostrarPanelVentas(){
        jSplitPane1.remove(2);
        jSplitPane1.setRightComponent(ven);
    
    }
    
    public void mostrarAlmacen(){
    jSplitPane1.remove(2);
    jSplitPane1.setRightComponent(alm);
    
    }
   
    public void mostrarGarantias(){
    
    jSplitPane1.remove(2);
    jSplitPane1.setRightComponent(ga);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PanelMenu = new javax.swing.JPanel();
        btnTablero = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(32767, 2));
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setBackground(new java.awt.Color(59, 78, 199));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setName(""); // NOI18N
        jSplitPane1.setPreferredSize(new java.awt.Dimension(494, 87));

        PanelMenu.setBackground(new java.awt.Color(104, 16, 16));
        PanelMenu.setLayout(new java.awt.GridLayout(0, 1, 1, 0));

        btnTablero.setBackground(new java.awt.Color(136, 235, 249));
        btnTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlopticadelaluz/Tablero2.png"))); // NOI18N
        btnTablero.setText("Tablero");
        btnTablero.setMaximumSize(new java.awt.Dimension(0, 0));
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });
        PanelMenu.add(btnTablero);

        jButton2.setBackground(new java.awt.Color(136, 235, 249));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlopticadelaluz/Ventas.png"))); // NOI18N
        jButton2.setText("Ventas");
        jButton2.setName(""); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton2);

        jButton3.setBackground(new java.awt.Color(136, 235, 249));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlopticadelaluz/Inventario.png"))); // NOI18N
        jButton3.setText("Almacen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton3);

        btnProductos.setBackground(new java.awt.Color(136, 235, 249));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlopticadelaluz/Cliente.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        PanelMenu.add(btnProductos);

        jButton4.setBackground(new java.awt.Color(136, 235, 249));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controlopticadelaluz/Reporte.png"))); // NOI18N
        jButton4.setText("Garantias");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton4);

        jButton6.setBackground(new java.awt.Color(136, 235, 249));
        jButton6.setText("Cerrar sesión");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton6);
        PanelMenu.add(filler1);

        jLabel1.setBackground(new java.awt.Color(140, 155, 31));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hora:");
        PanelMenu.add(jLabel1);

        jSplitPane1.setLeftComponent(PanelMenu);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            mostrarPanelVentas();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
    
        jSplitPane1.remove(2);
       jSplitPane1.setRightComponent(t);
    }//GEN-LAST:event_btnTableroActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        mostrarPanelProductos();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mostrarPanelVentas();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mostrarGarantias();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        
    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
            
            
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnTablero;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
